
services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx/
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "4443:4443"
#      - "443:443"
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
        - .env
    secrets:
      - wp_password
      - wp_admin_password
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
    env_file:
      - .env
    restart: always

#  db:
#    image: postgres
#    healthcheck:
#      test: ["CMD", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
#      interval: 10s
#      retries: 5
#      start_period: 30s
#      timeout: 10s

networks:
  inception:
    name: inception
    driver: bridge

secrets:
  db_password:
    file: db_password
  db_root_password:
    file: db_root_password
  wp_password:
    file: wp_password
  wp_admin_password:
    file: wp_admin_password

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/grebrune/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/grebrune/data/mariadb
