
services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx/
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "4443:4443"
#      - "443:443"
#    secrets:
#      - cr_secr
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
        - .env
#    secrets:
#      - db_secr
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
#    secrets:
#      - db_root_secr
    env_file:
      - .env
    restart: always

#  db:
#    image: postgres
#    healthcheck:
#      test: ["CMD", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
#      interval: 10s
#      retries: 5
#      start_period: 30s
#      timeout: 10s

networks:
  inception:
    name: inception
    driver: bridge

#secrets:
#  cr_secr:
#    file: ../secrets/credentials.txt
#  db_secr:
#    file: ../secrets/db_password.txt
#  db_root_secr:
#    file: ../secrets/db_root_password.txt

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/grebrune/Documents/github/5_Circle/Inception/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/grebrune/Documents/github/5_Circle/Inception/data/mariadb
